version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - python -m py_compile app.py
  post_build:
    commands:
      - zip -r app.zip . -x "*.git*" ".github/*" ".venv/*" "tests/*"

artifacts:
  files:
    - app.zip
